name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    strategy:
      matrix:
        on: [ ubuntu-22.04, windows-2022 ] # , macos-latest, windows-2022 not working for Jimver/cuda-toolkit@v0.2.16 at the moment
        version: [12.5.0]
    runs-on: ${{ matrix.on }} # ubuntu-latest currently equals to ubuntu 22.04
    continue-on-error: true
    env:
      libraryName: cuda-samples
    steps:
      - if: ${{ matrix.on == 'ubuntu-22.04' }}
        run: |
          sudo rm /var/lib/apt/lists/lock && \
          sudo apt-get update -y && \
          sudo apt-get upgrade -y && \
          sudo apt-get -y --no-install-recommends install \
          zip \
          unzip 

      # - name: Add msbuild to PATH
      #   if: ${{ matrix.on == 'windows-2022' }}
      #   uses: ilammy/msvc-dev-cmd@v1.12.1
      #   with:
      #     arch: x64
      #     toolset: 14.3
          
      # - name: Add msbuild to PATH
      #   if: ${{ matrix.on == 'windows-2022' }}
      #   uses: microsoft/setup-msbuild@v2
      #   with:
      #     vs-version: '[14.3,14.4)'
      #     msbuild-architecture: x64

      - name: Install MSVC
        if: ${{ matrix.on == 'windows-2022' }}
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: x64
          sdk: 10.0.22621.0
          vsversion: 2022

      - uses: Jimver/cuda-toolkit@v0.2.16
        if: ${{ matrix.on != 'windows-2022' }}
        id: cuda-toolkit-non-windows
        with:
          cuda: ${{ matrix.version }}
          method: "network"
          sub-packages: '["nvcc", "nvtx", "cudart"]'
          
      - uses: Jimver/cuda-toolkit@v0.2.16
        if: ${{ matrix.on == 'windows-2022' }}
        id: cuda-toolkit-windows
        with:
          cuda: ${{ matrix.version }}
          sub-packages: '["nvcc", "nvtx", "cudart", "visual_studio_integration"]'
        # use-local-cache: false
        # use-github-cache: false
        # sub-packages: '["nvcc", "visual_studio_integration", "cudart", "cublas", "cublas_dev", "thrust"]'
          

      - if: ${{ matrix.on != 'windows-2022' }}
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit-non-windows.outputs.cuda}}" && echo "Cuda install location: ${{steps.cuda-toolkit-non-windows.outputs.CUDA_PATH}}"
      
      - if: ${{ matrix.on == 'windows-2022' }}
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit-windows.outputs.cuda}}" && echo "Cuda install location: ${{steps.cuda-toolkit-windows.outputs.CUDA_PATH}}"
          
      - name: nvcc version
        run: nvcc --version
        
      - uses: actions/checkout@v4
        with:
          repository: NVIDIA/cuda-samples
          ref: ${{ env.tagName }}
          path: ${{ env.libraryName }}
          submodules: true
          
      - if: ${{ matrix.on == 'ubuntu-22.04' }}
        run: make || ls
        working-directory: ${{ env.libraryName }}/Samples/1_Utilities/deviceQuery
        
      - if: ${{ matrix.on == 'windows-2022' }}
        shell: cmd
        run: msbuild deviceQuery_vs2022.sln -target:deviceQuery -property:Configuration=Release && dir
        working-directory: ${{ env.libraryName }}/Samples/1_Utilities/deviceQuery
        
      - if: ${{ matrix.on == 'ubuntu-22.04' }}
        run: ./deviceQuery
        continue-on-error: true
        working-directory: ${{ env.libraryName }}/Samples/1_Utilities/deviceQuery
        
      - if: ${{ matrix.on == 'windows-2022' }}
        shell: cmd
        run: .\deviceQuery.exe
        continue-on-error: true
        working-directory: ${{ env.libraryName }}/bin/win64/Release
        
      - name: Archive Release
        if: ${{ matrix.on == 'ubuntu-22.04' }}
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: |
            deviceQuery
          directory: "${{ env.libraryName }}/Samples/1_Utilities/deviceQuery"
          filename: "deviceQuery-ubuntu-22.04-${{ github.ref_name }}.zip"
          
      - name: Archive Release
        if: ${{ matrix.on == 'windows-2022' }}
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: |
            deviceQuery.exe
          directory: "${{ env.libraryName }}/bin/win64/Release"
          filename: "deviceQuery-windows-server-2022-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        if: ${{ matrix.on == 'ubuntu-22.04' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.libraryName }}/Samples/1_Utilities/deviceQuery/deviceQuery-ubuntu-22.04-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release prebuilt
        if: ${{ matrix.on == 'windows-2022' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.libraryName }}/bin/win64/Release/deviceQuery-windows-server-2022-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
